# Generated by Django 5.2.7 on 2025-11-03 16:49

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog_app", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Bootstrap icon class, e.g., 'bi-play-circle'",
                        max_length=50,
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#4db8c4",
                        help_text="Hex color for category badge",
                        max_length=7,
                    ),
                ),
                (
                    "created_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
            ],
            options={
                "verbose_name_plural": "Categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("slug", models.SlugField(unique=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AlterModelOptions(
            name="comment",
            options={"ordering": ["-created_date"]},
        ),
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ["-published_date", "-created_date"]},
        ),
        migrations.AddField(
            model_name="comment",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="excerpt",
            field=models.TextField(
                blank=True,
                help_text="Brief summary for listings",
                max_length=300,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="featured_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="featured_images/"
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="is_featured",
            field=models.BooleanField(default=False, help_text="Display on homepage"),
        ),
        migrations.AddField(
            model_name="post",
            name="slug",
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="post",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Draft"),
                    ("published", "Published"),
                    ("archived", "Archived"),
                ],
                default="draft",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="updated_date",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="post",
            name="views_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="post",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="posts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="posts",
                to="blog_app.category",
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="posts", to="blog_app.tag"
            ),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(fields=["slug"], name="blog_app_po_slug_c9147f_idx"),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(
                fields=["status", "published_date"],
                name="blog_app_po_status_f89ae5_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="post",
            index=models.Index(
                fields=["category"], name="blog_app_po_categor_d06bbe_idx"
            ),
        ),
    ]
