# Generated by Django 5.2.7 on 2025-11-04 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog_app", "0002_category_tag_alter_comment_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="color",
            field=models.CharField(
                default="#DC143C",
                help_text="Hex color for category badge",
                max_length=7,
            ),
        ),
    ]
